# Ansible managed

  location = / {
        return 301 /fpgas;
    }

  location /fpgas/ {
    include proxy_params;
    proxy_pass http://unix:/run/gunicorn.sock;
    client_max_body_size 30M; # Allow uploads up to 30MB
  }
