---
- name: install uhubctl
  ansible.builtin.apt:
    name:
      - uhubctl

- name: set udev rule to give user access to turn on and off the usb ports
  template:
    src: templates/udev/52-uhubctl.rules.j2
    dest: /etc/udev/rules.d/52-uhubctl.rules
  notify:
    - Udev-reload
  tags:
    - staticips

