# Generated by Django 5.0.2 on 2025-01-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.IntegerField()),
                ("mac", models.CharField(blank=True, max_length=17)),
                ("serial_no", models.CharField(blank=True, max_length=8)),
                ("location", models.CharField(blank=True, max_length=30)),
                ("model", models.CharField(blank=True, max_length=30)),
                ("cable_color", models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
