# Generated by Django 6.0.2 on 2026-02-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pibfpgas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pi",
            name="board_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("arty_a7", "Arty A7"),
                    ("netv2", "NeTV2"),
                    ("ulx3s", "ULX3S"),
                    ("fomu", "Fomu"),
                    ("tt_asic", "Tiny Tapeout ASIC"),
                    ("tt_fpga", "Tiny Tapeout FPGA Emulation"),
                ],
                default="arty_a7",
                max_length=20,
            ),
        ),
    ]
