---
- name: Install wssh deb packages
  apt:
    name:
      - nginx
      - systemd
      - python3-pip
      - python3-venv
      - python3-cryptography
      - python3-bcrypt

- name: Install wssh pip packages
  pip:
    name:
      - webssh
    virtualenv: "/usr/local/venv/wssh"
    # virtualenv_site_packages: True
    virtualenv_command: "python3 -m venv --system-site-packages"

- name: systemd files
  copy:
    src: "files/etc/systemd/system/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - wssh.socket
  notify:
   - reload systemd
  tags:
    - wssh

- name: systemd files
  template:
    src: templates/wssh.service.j2
    dest: /etc/systemd/system/wssh.service
  notify:
   - reload systemd
   - restart wssh
  tags:
    - wssh

- name: Enable services
  systemd:
    service: "{{ item }}"
    enabled: yes
  with_items:
    - wssh.socket
    - wssh.service

- name: Deploy nginx conf
  template:
    src: "files/etc/nginx/includes/wssh.conf"
    dest: "/etc/nginx/includes/{{ conference_name }}-wssh.conf"
  tags:
    - pibsite
  notify: reload nginx

