---

eth_uplink_mac_address: 0c:c4:7a:16:3b:4b
eth_uplink_static: true
eth_uplink_static_address: 10.31.0.2
eth_uplink_static_netmask: 16

eth_local_mac_address: 0c:c4:7a:16:3b:4a
eth_local_address: 10.31.0.3
eth_local_netmask: 16
dhcp_range: 10.31.0.128,10.31.0.254,6h

pib_network: 10.31.0

firewall_internal_networks: [10.31.0.0/16]

user_name: videoteam

conference_name: pib
room_name: welland

time_zone: America/Los_Angeles

common_name: fpgas.online
subject_alt_names:
  - fpgas.mithis.com
  - welland.fpgas.mithis.com
  - welland.fpgas.online

streaming_frontend_aliases: []
streaming_frontend_hostname: fpgas.online
domain_name: "{{ streaming_frontend_hostname}}"

fixture_path: fpgas.online.json

# Tim's
# Netgear S3300-52X-PoE+
switch_base: base

switch:
    mac: 08:bd:43:6b:bb:e0
    oid: iso.3.6.1.2.1.105.1.1.1.3.1
    host: "10.1.5.11"

    # pi for maintenance.sh
    mpi_port: 3
    mpi_ip: "{{ pib_network }}.{{ 100+switch.mpi_port }}"

    nos:
    - { port: 3, mac: "e4:5f:01:8d:f7:17", sn: "f77b8415",
        model: "Raspberry_Pi_4_Model_B_Rev_1",
        loc: "", cable_color: "yellow" }
    - { port: 5, mac: "e4:5f:01:97:1f:7e", sn: "613a4524",
        loc: "", cable_color: "gray" }
    - { port: 7, mac: "e4:5f:01:97:32:d2", sn: "8483b266",
        loc: "", cable_color: "gray/white" }
    - { port: 25, mac: "b8:27:eb:47:9f:d1", sn: "",
        loc: "", cable_color: "" }
    - { port: 35, mac: "b8:27:eb:fc:4d:f8", sn: "",
        loc: "", cable_color: "" }

    SNMP_SWITCH_COMMUNITY: pib

pi_pw: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62636632383032633730383961613037383164363435396466646662613362656231633430623530
          3763303635616261613433633732333732653066393237660a663761396661306536373665663361
          37613266393363393430323836613537383765316338396361376639313439623239633566616166
          6636393830333664610a643332626261376639316535333232626134366366353633383530333438
          3762
