---
- name: Install certbot and the certbot nginx extension
  apt:
    name:
    - certbot
    - python3-certbot-nginx
  tags: le

# Check if the SSL key files already exhist on the server
- name: Check if fullchain.pem file exhists
  stat: path=/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
  register: fullchain_path
  tags: le
- name: Check if privkey.pem files exhists
  stat: path=/etc/letsencrypt/live/{{ domain_name }}/privkey.pem
  register: privkey_path
  tags: le

- name: create certificate
  command: "certbot --nginx -d {{ domain_name }} --email {{ letsencrypt_account_email }} --agree-tos --non-interactive"
  when: not privkey_path.stat.exists and not fullchain_path.stat.exists
  tags: le
