# daphne.yml
---
- name: pip install daphne
  pip:
    name:
    - daphne
    virtualenv: "{{ django_dir }}/venv"

- name: copy daphne socket file to /etc/systemd/system/daphne.socket
  template:
    src: templates/daphne.socket.j2
    dest: /etc/systemd/system/daphne.socket

- name: copy daphne systemd file to /etc/systemd/system/daphne.service
  template:
    src: templates/daphne.service.j2
    dest: /etc/systemd/system/daphne.service
  tags:
    - django

- name: Enable services
  systemd:
    service: "{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: started
  with_items:
    - daphne.socket
    - daphne.service
