# daphne.yml
---
- name: pip install daphne
  pip:
    name:
    - daphne
    virtualenv: "{{ django_dir }}/venv"

- name: copy daphne socket file to /etc/systemd/system/pib-daphne.sock/serv
  template:
    src: "templates/daphne.{{ item }}.j2"
    dest: "/etc/systemd/system/{{ django_project_name }}-daphne.{{ item }}"
  with_items:
    - socket
    - service
  tags:
    - pibsite

- name: Enable services
  systemd:
    service: "{{ django_project_name }}-daphne.{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: started
  with_items:
    - socket
    - service
  tags:
    - pibsite
