# install_django.yml
---
- name: python and friends
  apt:
    name:
    - python3-venv

- name: copy the core pib site files
  copy:
    src: "files/pib/pib"
    dest: "{{ app_dir }}"

- name: copy manage.py into site dir
  copy:
    src: "files/pib/manage.py"
    dest: "{{ app_dir }}"

- name: chmod u+x manage.py
  file:
    path: "{{ app_dir }}/manage.py"
    mode: 'u+x'

- name: PIP install snmp_switch site app
  ansible.builtin.pip:
    name: "git+https://github.com/CarlFK/pici.git#subdirectory=ansible/roles/site/files/pib/snmp_switch"
    virtualenv: "{{ app_dir }}/venv"

# change permissions of whole app_dir
# - name: Recursively change ownership of a directory
#   file:
#     path: "{{ app_dir }}"
#    state: directory
#    recurse: yes
#    group: wheel
#    mode: '0775'

# Run Django collectstatic
# - name: Run manage.py collectstatic
#   community.general.django_manage:
#     command: collectstatic
#     app_path: "{{ app_dir }}"
#     virtualenv: "{{ app_dir }}/venv"

# Run Django manage.py makemigrations
- name: Run manage.py makemigrations
  community.general.django_manage:
    command: makemigrations
    app_path: "{{ app_dir }}"
    virtualenv: "{{ app_dir }}/venv"

# Run Django manage.py migrate
- name: Run manage.py migrate
  community.general.django_manage:
    command: migrate
    app_path: "{{ app_dir }}"
    virtualenv: "{{ app_dir }}/venv"

- name: Load the initial_data fixture into the application
  community.general.django_manage:
    command: loaddata
    app_path: "{{ app_dir }}"
    fixtures: "{{ fixture_path }}"
    virtualenv: "{{ app_dir }}/venv"
  when: fixture_path is defined

# Change allowed hosts to include the server IP address
- name: add server IP address to allowed hosts
  lineinfile:
    path: "{{ app_dir }}/{{ django_project_name }}/settings.py"
    state: present
    regexp: '^ALLOWED_HOSTS = '
    line: "ALLOWED_HOSTS = ['{{ eth_uplink_static_address }}','{{ domain_name }}']"

