# install_django.yml
---
- name: create site dir
  file:
    path: "{{ django_dir }}/pib"
    state: directory
  tags:
    - django

- name: copy the core pib site files
  copy:
    src: "files/pib/pib/{{ item }}"
    dest: "{{ django_dir }}/pib/"
  loop:
    - __init__.py
    - settings.py
    - urls.py
    - asgi.py
    - local_settings.py
  tags:
    - django

# Change allowed hosts to include the server IP address
- name: add server IP address to allowed hosts
  lineinfile:
    path: "{{ django_dir }}/{{ django_project_name }}/local_settings.py"
    state: present
    regexp: '^ALLOWED_HOSTS = '
    line: "ALLOWED_HOSTS = ['{{ eth_uplink_static_address }}','{{ domain_name }}']"
  tags:
    - django

# set CSRF_TRUSTED_ORIGINS
- name: add server IP address to allowed hosts
  lineinfile:
    path: "{{ django_dir }}/{{ django_project_name }}/local_settings.py"
    state: present
    regexp: '^CSRF_TRUSTED_ORIGINS = '
    line: "CSRF_TRUSTED_ORIGINS = ['https://{{ domain_name }}']"
  tags:
    - django

- name: pass the pi's user pw
  lineinfile:
    path: "{{ django_dir }}/{{ django_project_name }}/local_settings.py"
    state: present
    regexp: '^PI_PW = '
    line: "PI_PW = '{{pi_pw|b64encode}}'"
  tags:
    - django

- name: sites's domain name
  lineinfile:
    path: "{{ django_dir }}/{{ django_project_name }}/local_settings.py"
    state: present
    regexp: '^DOMAIN_NAME = '
    line: "DOMAIN_NAME = '{{ domain_name }}'"
  tags:
    - django

- name: set static dir
  lineinfile:
    path: "{{ django_dir }}/{{ django_project_name }}/local_settings.py"
    state: present
    regexp: '^STATIC_ROOT = '
    line: "STATIC_ROOT = '{{ static_dir }}'"
  tags:
    - django

- name: copy manage.py into site dir
  copy:
    src: "files/pib/manage.py"
    dest: "{{ django_dir }}"
  tags:
    - django

- name: chmod u+x manage.py
  file:
    path: "{{ django_dir }}/manage.py"
    mode: 'u+x'
  tags:
    - django

# Run Django collectstatic
- name: Run manage.py collectstatic
  community.general.django_manage:
    command: collectstatic
    project_path: "{{ django_dir }}"
    virtualenv: "{{ django_dir }}/venv"
  tags:
    - django

# Run Django manage.py migrate
- name: Run manage.py migrate
  community.general.django_manage:
    command: migrate
    project_path: "{{ django_dir }}"
    virtualenv: "{{ django_dir }}/venv"
  tags:
    - django

- name: copy fixtures to remote box
  copy:
    src: "files/pib/pibfpgas/fixtures/{{ fixture_path }}"
    dest: "/tmp/"
  when: fixture_path is defined
  tags:
    - django

- name: Load the initial_data fixture into the application
  community.general.django_manage:
    command: loaddata
    project_path: "{{ django_dir }}"
    virtualenv: "{{ django_dir }}/venv"
    fixtures: "/tmp/{{ fixture_path }}"
  when: fixture_path is defined
  tags:
    - django

