# install_gunicorn.yml
---
- name: pip install gunicorn
  pip:
    name:
    - gunicorn
    virtualenv: "{{ django_dir }}/venv"
  tags:
    - pibsite

- name: copy gunicorn socket/service files to /etc/systemd/system/
  template:
    src: "templates/gunicorn.{{ item }}.j2"
    dest: "/etc/systemd/system/{{ django_project_name }}-gunicorn.{{ item }}"
  with_items:
    - socket
    - service
  tags:
    - pibsite

- name: Enable services
  systemd:
    service: "{{ django_project_name }}-gunicorn.{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: started
  with_items:
    - socket
    - service
  tags:
    - pibsite

# Ensure gunicorn socket and system service is running
# Not sure what needs to be started.  start both above fine?
- name: force systemd to reread configs
  systemd:
    daemon_reload: yes
- name: Start/Make sure the gunicorn.socket systemd service is running
  systemd:
    name: "{{ django_project_name }}-gunicorn.socket"
    state: started
  tags:
    - pibsite
