# install_gunicorn.yml
---
- name: pip install gunicorn
  pip:
    name:
    - gunicorn
    virtualenv: "{{ app_dir }}/venv"

- name: copy gunicorn socket file to /etc/systemd/system/gunicorn.socket
  template:
    src: templates/gunicorn.socket.j2
    dest: /etc/systemd/system/gunicorn.socket

- name: copy gunicorn systemd file to /etc/systemd/system/gunicorn.service
  template:
    src: templates/gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
  tags:
    - django

- name: Enable services
  systemd:
    service: "{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: started
  with_items:
    - gunicorn.socket
    - gunicorn.service

# Ensure gunicorn socket and system service is running
# Not sure what needs to be started.  start both above fine?
- name: force systemd to reread configs
  systemd:
    daemon_reload: yes
- name: Start/Make sure the gunicorn.socket systemd service is running
  systemd:
    name: gunicorn.socket
    state: started
