---

- name: create static content dir
  file:
    path: "{{ static_dir }}"
    state: directory

# password thing:
# https://github.com/huashengdun/webssh
# echo Zeij8shi|base64

- name: page of everything
  template:
    src: templates/index.html.j2
    dest: "{{ static_dir }}/index.html"
  tags:
    - cam
    - django
    - index.html

