---
- name: create static content dir
  file:
    path: "{{ static_dir }}"
    state: directory

# password thing:
# https://github.com/huashengdun/webssh
# echo Zeij8shi|base64

- name: page of everything
  template:
    src: templates/index.html.j2
    dest: "{{ static_dir }}/index.html"
  tags:
    - cam
    - django
    - index.html

- name: pages of pis
  template:
    src: templates/fpga.html.j2
    dest: "{{ static_dir }}/pi{{ item.port }}.html"
  with_items: "{{ switch.nos }}"
  tags:
    - cam
    - django
    - index.html

- name: assets
  copy:
    src: "files/static/{{item}}"
    dest: "{{ static_dir }}/{{item}}"
  with_items:
    - fpga.png
    - intro.png
  tags:
    - index.html

