---

- name: create static content dir
  file:
    path: "{{ static_dir }}"
    state: directory

- name: page of everything
  template:
    src: templates/index.html.j2
    dest: "{{ static_dir }}/index.html"
  tags:
    - cam
    - django
    - index.html

