---
- {include_tasks: nginx.yml, tags: le}
- {include_tasks: pib.yml, tags: [snmp, django] }
- {include_tasks: certbot.yml, tags: le}
- {include_tasks: index.yml, tags: index.html}
- {include_tasks: js_player.yml, tags: django}
- {include_tasks: gunicorn.yml, tags: django}
- {include_tasks: django.yml, tags: [snmp, django] }
- {include_tasks: snmp.yml, tags: [testsnmp, django] }
