---
- name: remove unneeded nginx conf
  file:
    path: "/etc/nginx/{{item}}"
    state: absent
  with_items:
    - sites-enabled/default
    - sites-enabled/pxe

- name: configure https vhost
  template:
    src: templates/nginx.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ domain_name}}-https.conf"
  notify: reload nginx
