---
- name: remove DCV nginx.confs
  file:
    path: /etc/nginx/{{ item }}
    state: absent
  loop:
    - rtmp/backend.conf
    - rtmp/frontend.conf
    - sites-available/default
    - sites-available/pxe
    - sites-enabled/pxe
    - sites-enabled/streaming-backend-http.conf
    - sites-enabled/streaming-backend-https.conf
    - sites-enabled/streaming-frontend-http.conf
    - sites-enabled/streaming-frontend-https.conf
  notify: reload nginx

- name: disable default configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: configure https vhost
  template:
    src: templates/https-vhost.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ domain_name}}-https.conf"
  notify: reload nginx
