---
- name: remove unneeded nginx conf
  file:
    path: "/etc/nginx/{{item}}"
    state: absent
  with_items:
    - sites-enabled/default
    - sites-enabled/pxe

- name: Create etc/nginx/includes dir
  ansible.builtin.file:
    path: /etc/nginx/includes
    state: directory
