---
- name: PIP install pibfpgas site app
  ansible.builtin.pip:
    name: "pibfpgas @ git+https://github.com/CarlFK/pici.git#subdirectory=ansible/roles/site/files/pib/pibfpgas"
    virtualenv: "{{ django_dir }}/venv"
    state: forcereinstall
  tags:
    - pibfpgas
    - django

- name: Install nginx conf
  ansible.builtin.copy:
    src: files/pib/pibfpgas/nginx/pibfpgas.conf
    dest: "/etc/nginx/includes/{{ conference_name }}-pibfpgas.conf"
  tags:
    - pibfpgas
    - django

- name: Install demo code on pi
  ansible.posix.synchronize:
    src: files/pib/pibfpgas/Demos
    dest: "{{nfs_root}}/root/home/pi"
  tags:
    - pibfpgas
    - django
    - demos
