---
- name: PIP install pibup site app
  ansible.builtin.pip:
    name: "pibup @ git+https://github.com/CarlFK/pici.git#subdirectory=ansible/roles/site/files/pib/pibup"
    virtualenv: "{{ django_dir }}/venv"
    state: forcereinstall
  tags:
    - pibup
    - django

- name: nginx/pibup.conf
  copy:
    src: files/pib/pibup/nginx/pibup.conf
    dest: "/etc/nginx/includes/{{ conference_name }}-pibup.conf"
  tags:
    - pibup
    - django


