---
- name: Install redis
  apt:
    name:
    - redis
  tags:
    - pistat

- name: PIP install pistat site app
  ansible.builtin.pip:
    name: "pistat @ git+https://github.com/CarlFK/pici.git#subdirectory=ansible/roles/site/files/pib/pistat"
    virtualenv: "{{ django_dir }}/venv"
    state: forcereinstall
  tags:
    - pistat

- name: status chat js
  copy:
    src: files/pib/pistat/src/pistat/static/dcws.js
    dest: "{{ static_dir }}/dcws.js"
  tags:
    - pistat
    - index.html

- name: Install nginx streaming conf
  ansible.builtin.copy:
    src: files/pib/pistat/nginx/pistat.conf
    dest: "/etc/nginx/includes/{{ conference_name }}-pistat.conf"
  tags:
    - pistat

- name: copy scripts into usr/local/bin
  copy:
    src: "pib/pistat/scripts/{{ item }}"
    dest: "/usr/local/bin"
    mode: preserve
  loop:
    - send.py
    - send_stat.py
  tags:
    - pistat

- name: copy conf into /etc/dnsmasq.d
  copy:
    src: pib/pistat/dnsmasq/send_stat.conf
    dest: /etc/dnsmasq.d/send_stat.conf
    mode: preserve
  tags:
    - pistat

- name: restart dnsmasq
  systemd:
    name: dnsmasq
    state: restarted
  tags:
    - pistat

