---
- name: populate /etc/environment
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - key: SNMP_SWITCH_USERNAME
      value: "{{ switch.SNMP_SWITCH_USERNAME }}"
      hint: -u
    - key: SNMP_SWITCH_SECURITY_LEVEL
      value: "{{ switch.SNMP_SWITCH_SECURITY_LEVEL }}"
      hint: -l
    - key: SNMP_SWITCH_AUTH_PROTOCOL
      value: "{{ switch.SNMP_SWITCH_AUTH_PROTOCOL }}"
      hint: -a
    - key: SNMP_SWITCH_AUTHKEY
      value: "{{ switch.SNMP_SWITCH_AUTHKEY }}"
      hint: -A
    - key: SNMP_SWITCH_PRIV_PROTOCOL
      value: "{{ switch.SNMP_SWITCH_PRIV_PROTOCOL }}"
      hint: -x
    - key: SNMP_SWITCH_PRIVKEY
      value: "{{ switch.SNMP_SWITCH_PRIVKEY }}"
      hint: -X
    - key: SNMP_SWITCH_HOST
      value: "{{ switch.host }}"
    - key: SNMP_SWITCH_OID
      value: "{{ switch.oid }}"
    - key: pi_ports
      value: "\"{% for pi in switch.nos %}{{pi.port}} {% endfor %}\""
  tags: snmp

- name: copy poe.sh and allpoe.sh into usr/local/bin
  copy:
    src: "pib/snmp_switch/scripts/{{ item }}"
    dest: "/usr/local/bin"
    mode: preserve
  loop:
    - poe.sh
    - allpoe.sh
  tags: snmp

# pip install "django[bcrypt] @ git+ssh://git@github.com/django/django.git" should work fine.
- name: PIP install snmp_switch site app
  ansible.builtin.pip:
    name: "snmp_switch[cli] @ git+https://github.com/CarlFK/pici.git#subdirectory=ansible/roles/site/files/pib/snmp_switch"
    virtualenv: "{{ app_dir }}/venv"
    state: forcereinstall
  tags:
    - snmp

- name: nginx/snmp_switch.conf
  copy:
    src: files/pib/snmp_switch/nginx/snmp_switch.conf
    dest: "/etc/nginx/includes/{{ conference_name }}-snmp_switch.conf"
  tags:
    - snmp


