# install_uvicorn.yml
---
- name: pip install uvicorn
  pip:
    name:
    - uvicorn
    virtualenv: "{{ django_dir }}/venv"

- name: copy uvicorn systemd file to /etc/systemd/system/uvicorn.service
  template:
    src: templates/uvicorn.service.j2
    dest: /etc/systemd/system/uvicorn.service
  tags:
    - django

- name: Enable services
  systemd:
    service: "{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: started
  with_items:
    - uvicorn.service
  tags:
    - django

- name: Start/Make sure uvicorn.service systemd service is running
  systemd:
    daemon_reload: yes
    state: started
    name: uvicorn.service
  tags:
    - django
