---
- name: Install packages
  apt:
    name:
      - ssh-import-id
      - vim
      - tmux
      - git
      - etckeeper
      - sshfs
      - tio
      - rsync
      - openocd
      - fxload
      - python3-venv
    install_recommends: yes
  tags:
    - img
