---

- name: apt update/upgrade
  apt:
    # name: "*"
    upgrade: true
    state: latest
    update_cache: true
    cache_valid_time: 86400

# something odd here...
# dpkg-divert: error: rename involves overwriting '/usr/share/vim/vim82/doc/help.txt.vim-tiny' with different file '/usr/share/vim/vim82/doc/help.txt', not allowed
# so remove it
- name: apt remove tiny-vim
  apt:
    name:
      - vim-tiny
    state: absent

- name: Install packages
  apt:
    name:
      - overlayroot
      - ssh-import-id
      - vim
      - tmux
      - screen
      - git
      - etckeeper
      - sshfs
      - atftpd
      - tio
      - minicom
      - rsync
      - openocd
      - fxload
      - openfpgaloader
      - openwince-jtag
      - python3-full
      - python3-venv
      - python3-pip
      - python3-tqdm
      - python3-numpy
      - software-properties-common
    install_recommends: yes
  tags:
    - img

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

