---

# something odd here...
# dpkg-divert: error: rename involves overwriting '/usr/share/vim/vim82/doc/help.txt.vim-tiny' with different file '/usr/share/vim/vim82/doc/help.txt', not allowed
# so remove it
- name: apt remove tiny-vim
  apt:
    name:
      - vim-tiny
    state: absent

- name: Install packages
  apt:
    name:
      - ssh-import-id
      - vim
      - tmux
      - git
      - etckeeper
      - sshfs
      - tio
      - rsync
      - openocd
      - fxload
      - python3-venv
      - software-properties-common
    install_recommends: yes
  tags:
    - img

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

