- name: let kernel figure out nfs ver
  # (4.x doesn't work with overlayfs)
  # sed -i "/nfsroot/s/,nfsvers=4.2//" /boot/firmware/cmdline.txt
  replace:
    path: /boot/firmware/cmdline.txt
    regexp: "nfsvers=4.2"
    replace: ""

