- name: systemd pistat_ssh.service
  template:
    src: files/pistat_ssh.service.j2
    dest: /etc/systemd/system/pistat_ssh.service
  notify: reload-systemd
  tags:
    - pistat

- name: enable and start services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    # - cam
    - pistat_ssh
  tags:
    - pistat

