- name: systemd pistat_ssh.service
  template:
    src: "files/{{ item }}.service"
    dest: "/etc/systemd/system/{{ item }}.service"
  notify: reload-systemd
  with_items:
    - pistat_ssh
    - pistat_cam
    - pistat_info
    - pistat_shutdown
  tags:
    - pistat

- name: enable and start services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - pistat_ssh
    - pistat_cam
    - pistat_info
    - pistat_shutdown
  tags:
    - pistat

