---
- name: Install packages
  apt:
    name:
      - unzip
      - parted
      - rsync
    install_recommends: yes
  tags:
    - img

- name: create pib cache dir
  file:
    path: "{{ cache_dir }}"
    state: directory

- name: Download pi sd card img file
  get_url:
    url: "{{ img_host }}/{{ img_path }}/{{ zip_name }}"
    dest: "{{ cache_dir }}"
    force: False
  tags:
    - img
  # creates: "{{ cache_dir }}/{{ zip_name }}"

- name: extract files from raspios.img.xz
  script: files/img2files.sh {{ zip_name }} {{ img_name }} {{ dist }}
  args:
    chdir: "{{ cache_dir }}"
    creates: "{{ nfs_root }}/root/home"
  tags:
    - img
