---
- name: Install packages
  apt:
    name:
      - unzip
      - parted
      - rsync
    install_recommends: yes
  tags:
    - img

- name: create pib cache dir
  file:
    path: "{{ cache_dir }}"
    state: directory

- name: Download pi sd card img file
  get_url:
    url: "{{ img_host }}/{{ img_path }}/{{ zip_name }}"
    dest: "{{ cache_dir }}"
    force: False

- name: extract files from raspios.img.xz
  script: files/img2files.sh {{ zip_name }} {{ img_name }} {{ dist }}
  args:
    chdir: "{{ cache_dir }}"
    creates: "{{ nfs_root }}/root/home"

- name: create scripts dir
  file:
    path: /root/scripts
    state: directory

- name: install scripts to manage pi states
  copy:
    src: "files/scripts"
    dest: "/root"
    mode: preserve
  tags:
    - scripts

- name: install scripts to manage pi states II
  copy:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
    mode: preserve
  with_items:
   - scripts/burn.sh
   - scripts/maintenance.sh
   - scripts/mktftpln.sh
   - scripts/production.sh
   # - netgear/poe.sh
   # - netgear/allpoe.sh

