#!/bin/bash
set -ex

# maintenance.sh
# used to alter the files on the file server
# with commands that are easier to run in/on a pi
# give pi's (all of them) rw access to the nfs shares, mount /boot
# all of them, so best to:
#  shut them all off
#  maintenance.sh
#  boot one pi
#  use it to apt-whatever
#  shut it off
#  normal.sh
# boot all the pies

# this should probably be a .conf and or generated by ansible

dist=bullseye
p=/srv/nfs/rpi/${dist}
boot=${p}/boot
root=${p}/root

# pi overlayroot off
sed -i "/.*/s/overlayroot=tmpfs/overlayroot=/" ${boot}/cmdline.txt

# pi fstab: automount,rw / and /boot
sed -i "\@${p}.*\snfs\s@s@\bnoauto\b@auto@" ${root}/etc/fstab
sed -i "\@${p}.*\snfs\s@s@\bro\b@rw@" ${root}/etc/fstab

# server nfs shares rw
sed -i "/.*/s/ro,/rw,/" /etc/exports
systemctl restart nfs-server.service

