---
- name: self-sign certificate
  command: "openssl x509 -req -sha256 -days 365 -in {{ csr_path }} \
            -signkey {{ privatekey_path }} -out {{ certificate_path }}"
  when:
    - csr_result is changed
  tags:
    - tls-certificates
  register: self_sign_result

- name: generate full chain
  shell: /bin/cat {{ certificate_path|quote }} > {{ fullchain_path|quote }}
  when:
    - self_sign_result is changed
  tags:
    - tls-certificates
