---
- name: install nginx
  apt:
    name: nginx-extras

- name: remove default nginx vhost
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: place pxe nginx vhost
  template:
    src: templates/pxe.j2
    dest: /etc/nginx/sites-available/pxe
  notify: reload nginx

- name: enable pxe nginx vhost
  file:
    state: link
    src: /etc/nginx/sites-available/pxe
    dest: /etc/nginx/sites-enabled/pxe
  notify: reload nginx
