---
- name: Install nftables
  apt:
    name:
    - nftables
    - nmap

- name: Write nftables rules
  template:
    src: templates/nftables.conf.j2
    dest: /etc/nftables.conf
    mode: 0755
  notify: reload nftables
  tags:
    nftables

- name: Enable nftables service
  systemd:
    service: nftables.service
    enabled: yes
    state: restarted
  tags:
    nftables
