---
- name: Install packages
  apt:
    name:
      - pwgen
    install_recommends: yes
  tags:
    - img


- name: root the tftp so dumb pi can find bootcode.bin
  file:
    src: "{{ nfs_root }}/boot/bootcode.bin"
    dest: "/srv/tftp/bootcode.bin"
    state: link

- name: link pi serial-num to boot dir, cuz that is how it works.
  file:
    src: "{{ nfs_root }}/boot"
    dest: "/srv/tftp/{{ item }}"
    state: link
  with_items:
    "{{ hosts }}"

- name: save the original config.txt and cmdline.txt
  command: mv "{{ nfs_root }}/boot/{{ item }}" "{{ nfs_root }}/boot/{{ item }}.org"
  args:
    removes: "{{ nfs_root }}/boot/{{ item }}"
    creates: "{{ nfs_root }}/boot/{{ item }}.org"
  with_items:
    - config.txt
    - cmdline.txt

- name: replace config/cmdline with netbootie versions
  copy:
    src: "files/boot/{{ item }}"
    dest: "{{ nfs_root }}/boot/{{ item }}"
  with_items:
    - config.txt
    - cmdline.txt

- name: remind pi where root fs is
  copy:
    src: "files/etc/fstab"
    dest: "{{ nfs_root }}/root/etc/fstab"

- name: don't resize the root fs
  file:
    path: "{{ nfs_root }}/root/etc/init.d/resize2fs_once"
    state: absent

- name: don't manage a swap file
  file:
    path: "{{ nfs_root }}/etc/systemd/system/multi-user.target.wants/dphys-swapfile.service"
    state: absent

- name: display IP, pw and things on console
  copy:
    src: "files/etc/issue"
    dest: "{{ nfs_root }}/root/etc/issue"

- name: create a password and tell everyone
  script: files/pipw.sh "{{user}}"
  args:
    chdir: "{{nfs_root}}"
    creates: "{{nfs_root}}/root/etc/ssh/password.txt"

- name: enable sshd
  file:
    path: "{{ nfs_root }}/boot/ssh"
    state: touch

- name: avoid [FAILED] Failed to start Set console font and keymap.
  file:
    path: "{{ nfs_root }}/root/etc/systemd/system/multi-user.target.wants/console-setup.service"
    state: absent

- name: avoid Wi-Fi is currently blocked by rfkill.
  file:
    path: "{{ nfs_root }}/root/etc/profile.d/wifi-check.sh"
    state: absent

# FIXME
# - name: avoid [FAILED] Failed to start Hostname Service.
#  file:
#    path: "{{ nfs_root }}/"
#    state: absent
#

- name: set US keyboard
  copy:
    src: "files/etc/keyboard"
    dest: "{{ nfs_root }}/root/etc/keyboard"

- name: login spam
  copy:
    src: "files/etc/show_info.sh"
    dest: "{{ nfs_root }}/root/etc/show_info.sh"


- name: sshd password settings
  copy:
    src: "files/etc/ssh/sshd_config.d/password.conf"
    dest: "{{ nfs_root }}/root/etc/ssh/sshd_config.d/password.conf"

