---
- name: link bootcode.bin in tftp root because pi netboot not too smart.
  file:
    src: "{{ nfs_root }}/boot/bootcode.bin"
    dest: "/srv/tftp/bootcode.bin"
    state: link

- name: link pi serial-num to boot dir, cuz that is how it works.
  file:
    src: "{{ nfs_root }}/boot"
    dest: "/srv/tftp/{{ item.sn }}"
    state: link
  with_items:
    "{{ switch.nos }}"
  tags:
    - pibs

- name: save the original config.txt, cmdline.txt, fstab
  command: mv "{{ nfs_root }}/{{ item }}" "{{ nfs_root }}/{{ item }}.org"
  args:
    removes: "{{ nfs_root }}/{{ item }}"
    creates: "{{ nfs_root }}/{{ item }}.org"
  with_items:
#    - "boot/config.txt"
    - "boot/cmdline.txt"
    - "boot/user-data"
    - "root/fstab"
  tags:
    - netboot

- name: replace cmdline with netbootie versions
  template:
    src: "templates/boot/{{ item }}.j2"
    dest: "{{ nfs_root }}/boot/{{ item }}"
  with_items:
    - cmdline.txt
  tags:
    - cmdline
    - netboot

- name: fstab - replace local fs to nfs
  template:
    src: "templates/etc/{{ item }}.j2"
    dest: "{{ nfs_root }}/root/etc/{{ item }}"
  with_items:
    - fstab
  tags:
    - cmdline
    - netboot

- name: install nfs-common into pi's fs
  command: chroot-mount-pi-fs.bash "{{ nfs_root }}" "/tmp/pi" "{{ item }}"
  with_items:
    - "apt install -y nfs-common"
  tags:
    - netboot
    - qemu


