---
- name: link bootcode.bin in tftp root because pi netboot not too smart.
  file:
    src: "{{ nfs_root }}/boot/bootcode.bin"
    dest: "/srv/tftp/bootcode.bin"
    state: link

- name: link pi serial-num to boot dir, cuz that is how it works.
  file:
    src: "{{ nfs_root }}/boot"
    dest: "/srv/tftp/{{ item.sn }}"
    state: link
  with_items:
    "{{ switch.nos }}"

- name: save the original config.txt and cmdline.txt
  command: mv "{{ nfs_root }}/boot/{{ item }}" "{{ nfs_root }}/boot/{{ item }}.org"
  args:
    removes: "{{ nfs_root }}/boot/{{ item }}"
    creates: "{{ nfs_root }}/boot/{{ item }}.org"
  with_items:
    - config.txt
    - cmdline.txt

- name: replace config/cmdline with netbootie versions
  copy:
    src: "files/boot/{{ item }}"
    dest: "{{ nfs_root }}/boot/{{ item }}"
  with_items:
    - config.txt
    - cmdline.txt

- name: replace local SD card with nfs mount point
  copy:
    src: "files/etc/fstab"
    dest: "{{ nfs_root }}/root/etc/fstab"
