---
- name: Install packages
  apt:
    name:
      - pwgen
    install_recommends: yes
  tags:
    - img

- name: display IP, pw and things on console
  copy:
    src: "files/etc/issue"
    dest: "{{ nfs_root }}/root/etc/issue"

- name: set the password and tell everyone
  script: files/pipw.sh "{{user}}" "{{pi_pw}}"
  args:
    chdir: "{{nfs_root}}/root"
    creates: "{{nfs_root}}/root/etc/ssh/password.txt"
  tags:
  - pipw

- name: enable sshd
  file:
    path: "{{ nfs_root }}/boot/ssh"
    state: touch

- name: get fixed sshswitch
  get_url:
    url: "https://raw.githubusercontent.com/RPi-Distro/raspberrypi-sys-mods/{{ dist }}/debian/raspberrypi-sys-mods.sshswitch.service"
    dest: "{{ nfs_root }}/root/etc/systemd/system/multi-user.target.wants/sshswitch.service"
  when: False

- name: sshd password settings
  copy:
    src: "files/etc/ssh/sshd_config.d/password.conf"
    dest: "{{ nfs_root }}/root/etc/ssh/sshd_config.d/password.conf"

- name: Generate ssh keys for server user
  ansible.builtin.user:
    name: "{{ user_name }}"
    generate_ssh_key: true  # This will not overwrite an existing SSH key.
    ssh_key_type: ed25519

- name: Copy authorized_keys to pi pi and root
  ansible.builtin.copy:
    remote_src: true
    src: "/home/{{ user_name }}/.ssh/authorized_keys"
    dest: "/srv/nfs/rpi/{{dist}}/root/{{item}}/.ssh/authorized_keys"
  with_items:
    - root
    - home/pi

