---
- name: display IP, pw and things on console
  copy:
    src: "files/etc/issue"
    dest: "{{ nfs_root }}/root/etc/issue"

- name: set the password and tell everyone
  script: files/pipw.sh "{{user}}" "{{pi_pw}}"
  args:
    chdir: "{{nfs_root}}/root"
    creates: "{{nfs_root}}/root/etc/ssh/password.txt"
  tags:
  - pipw

- name: enable sshd
  file:
    path: "{{ nfs_root }}/boot/ssh"
    state: touch

- name: get fixed sshswitch
  get_url:
    url: "https://raw.githubusercontent.com/RPi-Distro/raspberrypi-sys-mods/{{ dist }}/debian/raspberrypi-sys-mods.sshswitch.service"
    dest: "{{ nfs_root }}/root/etc/systemd/system/multi-user.target.wants/sshswitch.service"
  when: False

- name: sshd password settings
  copy:
    src: "files/etc/ssh/sshd_config.d/password.conf"
    dest: "{{ nfs_root }}/root/etc/ssh/sshd_config.d/password.conf"

- name: Generate ssh keys for server user
  ansible.builtin.user:
    name: "{{ user_name }}"
    generate_ssh_key: true  # This will not overwrite an existing SSH key.
  tags:
  - keys

- name: create .ssh dirs
  file:
    path: "{{ nfs_root }}/root/{{ item }}/.ssh"
    state: directory
  with_items:
    - root
    - home/pi
  tags:
  - keys

- name: Generate ssh keys for pi users pi and root
  community.crypto.openssh_keypair:
    path: "{{ nfs_root }}/root/{{ item }}/.ssh/id_ssh_rsa"
  with_items:
    - root
    - home/pi
  tags:
  - keys

- name: Set authorized key for pi root user
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/home/{{ user_name }}/.ssh/id_rsa.pub') }}"
    path: "/srv/nfs/rpi/{{dist}}/root/{{item}}/.ssh/authorized_keys"
  with_items:
    - root
  tags:
  - keys
  when: false

- name: Copy keys to pi pi and root authorized_keys
  ansible.builtin.copy:
    remote_src: true
    src:  "/home/{{ user_name }}/.ssh/id_rsa.pub"
    dest: "/srv/nfs/rpi/{{dist}}/root/{{item}}/.ssh/authorized_keys"
  with_items:
    - root
    - home/pi
  tags:
  - keys

