---
- name: restart network-manager
  systemd:
    name: NetworkManager
    state: restarted

- name: restart networking
  systemd:
    name: networking
    state: restarted

- name: restart dnsmasq
  systemd:
    name: dnsmasq
    state: restarted

- name: reboot
  when: ansible_connection != 'local'
  command: shutdown -r now "Reboot triggered by Ansible"
  async: 0
  poll: 0
  ignore_errors: true

- name: wait for reboot
  when: ansible_connection != 'local'
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ ansible_port | default(22) }}"
    delay: 1
    timeout: 300
  delegate_to: localhost
  become: false
