---
- name: restart network-manager
  systemd:
    name: NetworkManager
    state: restarted

- name: restart networking
  systemd:
    name: networking
    state: restarted

- name: restart dnsmasq
  systemd:
    name: dnsmasq
    state: restarted
