---
- hosts: pib
  roles:
  - pxe/dhcp-server
  - firewall
  - sshd
  - img
  - fixpi
  - pxe
  - nfs

- hosts: wssh
  roles:
  - wssh

- hosts: onpi
  roles:
  # - onpi
  - cam/pi

- hosts: streaming-backends
  roles:
  - cam/srv/base
  - cam/srv/backend

- hosts: streaming-frontends
  roles:
  - cam/srv/base
  - cam/srv/frontend


