---
- hosts: nbp
  roles:
  - firewall
  - nfs
  - img
  - fixpi
  - pxe

- hosts: uhubctl
  roles:
  - uhubctl

- hosts: pig
  roles:
  - site
  - wssh
  - cam/stream-server
  - ci

- hosts: pi
  roles:
  - cam/pi
  - onpi

