---
- name: install gst packages
  apt:
    name:
      - gstreamer1.0-tools
  tags:
    - streaming

- name: cam script
  copy:
    src: files/frontend.conf
    dest: /usr/local/bin/gst-libcam.sh
    mode: u+x
  tags:
    cam

