---
- name: remove DCV nginx.confs
  file:
    path: /etc/nginx/rtmp/{{ item }}
    state: absent
  loop:
    - backend.conf
    - frontend.conf
  notify: reload nginx
  tags:
    - streaming

- name: install tiny rtmp nginx conf
  template:
    src: templates/pib.conf.j2
    dest: /etc/nginx/rtmp/pib.conf
  tags:
    streaming

