---
- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: reload-systemd
  systemd:
    daemon_reload: yes

- name: Mount all
  ansible.builtin.command: mount -a

