---
- name: page of video players
  template:
    src: templates/index.html.j2
    dest: /srv/streaming/www/index.html
  tags:
    - cam
    - index.html

- name: js video player
  copy:
    src: files/videojs-contrib-media-sources.js
    dest: /srv/streaming/www/videojs-contrib-media-sources.js
  tags:
    - cam

